var json = {
	"vehicle1": {
		"owner": ["Owner:", "Brent"],
		"make": ["Make:", "Ford"],
		"model": ["Model:", "Explorer"],
		"mileage": ["Mileage:", "60000"],
		"transmission": ["Transmission:", "Automatic"],
		"condition": ["Condition:", "10"],
		"oilCB": ["Oil and Filter:", "checked"],
		"tireRotationCB": ["Tire Rotation:", "null"],
		"oilChange": ["Last Oil Change:", "2012-07-24"],
		"airChange": ["Last Air Filter Change:", "2012-07-24"],
		"notes": ["Notes:", "No concerns."],
	},
	"vehicle2": {
		"owner": ["Owner:", "Steph"],
		"make": ["Make:", "Chevy"],
		"model": ["Model:", "Silverado"],
		"mileage": ["Mileage:", "70000"],
		"transmission": ["Transmission:", "Manual"],
		"condition": ["Condition:", "5"],
		"oilCB": ["Oil and Filter:", "null"],
		"tireRotationCB": ["Tire Rotation:", "checked"],
		"oilChange": ["Last Oil Change:", "2012-07-25"],
		"airChange": ["Last Air Filter Change:", "2012-07-25"],
		"notes": ["Notes:", "Some concerns."],
	},
	"vehicle3": {
		"owner": ["Owner:", "Linda"],
		"make": ["Make:", "Jeep"],
		"model": ["Model:", "Cherokee"],
		"mileage": ["Mileage:", "80000"],
		"transmission": ["Transmission:", "Automatic"],
		"condition": ["Condition:", "1"],
		"oilCB": ["Oil and Filter:", "checked"],
		"tireRotationCB": ["Tire Rotation:", "checked"],
		"oilChange": ["Last Oil Change:", "2012-07-26"],
		"airChange": ["Last Air Filter Change:", "2012-07-26"],
		"notes": ["Notes:", "Nothing but concerns."],
	}
};
